sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss: # TODO 改成github上传服务
    access-key-id: test-access-key-id
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: test-bucket-name
    access-key-secret: test-access-key-secret
  redis:
    host: localhost
    port: 6379
    password: root
    database: 10
  wechat:
    appid: wx01d6a4a3ae086dd0
    secret: bfeb72d822cfe992adce2a93db856920
    mchid: xx
    mch-serial-no: 4B
    private-key-file-path: D:\pay\apiclient_key.pom
    api-v3-key: CZB
    we-chat-pay-cert-file-path: D:\pay\apiclient_key.pom
    notify-url: xx
    refund-notify-url: xx