sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss: # TODO 配置阿里云OSS服务
    access-key-id: test-access-key-id
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: test-bucket-name
    access-key-secret: test-access-key-secret
  redis:
    host: localhost
    port: 6379
    password: root
    database: 10